### ISSUE TITLE
Get-InfluxDbDatabase should be named Get-InfluxDbDatabases

### ISSUE THREAD

**Issue by frankvaneykelen** [nicholasdille/PowerShell-InfluxDb#2]
This would better represent what is does: Returns a **list** of all databases on your instance (https://docs.influxdata.com/influxdb/v1.8/query_language/explore-schema/#show-databases).

**Comment by frankvaneykelen** [comment]
The same goes for `Get-InfluxDbMeasurement` (`Invoke-InfluxDbApi -Query 'SHOW MEASUREMENTS' -Database $Database`)

**Comment by nicholasdille** [comment]
Thanks for your feedback and sorry for the late reply.

In PowerShell cmdlets are named VERB-NOUN with a singular noun because it is meant to return one or more objects.

**Comment by frankvaneykelen** [comment]
Thanks, learned something today: "Best Practice: It is recommended to use an English singular noun for cmdlet, do not use plural noun."
https://powershell-guru.com/powershell-best-practice-6-use-singular-noun/
